(println "Zero ----------------------------------------")
(println (zero? 0))
(println "Pos ----------------------------------------")
(println (pos? -1))
(println "neg ----------------------------------------")
(println (neg? -1))
(println "even ----------------------------------------")
(println (even? 2))
(println "odd ----------------------------------------")
(println (odd? 2))
(println "number ----------------------------------------")
(println (number? -1))
(println "integer ----------------------------------------")
(println (integer? -1))
(println "float ----------------------------------------")
(println (float? -1))

